# -*- coding: utf-8 -*-
"""tema15.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiPp9V2rmHy6pTkWfJ1TWcfm_18e-1nt
"""

texto = "hola como estas?"
print(type(texto))

numeros = 715
print(type(numeros))

print("que tengas 'bonito' dia")

palabras = "Buenos dias como estas?"
print(palabras[0])
print(palabras[-1])

python = "muy bueno lo quiero muchi"
print(python[0:3:2])
print(python[11:18:2])

Y = "Vamos a la clase"
print(Y.upper())

print(Y.lower())

print(Y.split())

print(Y.title())

print(Y.swapcase())

print(Y.replace("Vamos", "vamos"))

print(Y.lstrip())

print(Y.rstrip())


x = "programa en python"

print(x.split())
['programa', 'en', 'python']

email = "nombre.apellido@ejemplo.tld"
print(email.split('@'))
['nombre.apellido', 'ejemplo.tld']

mensaje="Mi mejor {} se llama {} y tiene {} años".format("Amigo", "Celso", "37")
print(mensaje)

ciudad = "san luis potosi"
pais = "mexico"
continente = "america"
print(f"Mi ciudad es {ciudad} y se encuentra en {pais}, que es parte de {continente}")